
package oscar.bustos.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SumarService", targetNamespace = "http://ws.bustos.oscar/", wsdlLocation = "http://localhost:8084/WSSumar/Sumar?wsdl")
public class SumarService
    extends Service
{

    private final static URL SUMARSERVICE_WSDL_LOCATION;
    private final static WebServiceException SUMARSERVICE_EXCEPTION;
    private final static QName SUMARSERVICE_QNAME = new QName("http://ws.bustos.oscar/", "SumarService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8084/WSSumar/Sumar?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SUMARSERVICE_WSDL_LOCATION = url;
        SUMARSERVICE_EXCEPTION = e;
    }

    public SumarService() {
        super(__getWsdlLocation(), SUMARSERVICE_QNAME);
    }

    public SumarService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SUMARSERVICE_QNAME, features);
    }

    public SumarService(URL wsdlLocation) {
        super(wsdlLocation, SUMARSERVICE_QNAME);
    }

    public SumarService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SUMARSERVICE_QNAME, features);
    }

    public SumarService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SumarService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Sumar
     */
    @WebEndpoint(name = "SumarPort")
    public Sumar getSumarPort() {
        return super.getPort(new QName("http://ws.bustos.oscar/", "SumarPort"), Sumar.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Sumar
     */
    @WebEndpoint(name = "SumarPort")
    public Sumar getSumarPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.bustos.oscar/", "SumarPort"), Sumar.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SUMARSERVICE_EXCEPTION!= null) {
            throw SUMARSERVICE_EXCEPTION;
        }
        return SUMARSERVICE_WSDL_LOCATION;
    }

}
